name: "🐞 Bug report"
description: "Report an inssue"
title: "bug: title (<-- change me)"
labels: ["bug", "needs-triage"]
body: 
  - attributes: 
      value: |
          # crDroid bug report
          
          Important to note that your issue may have already been reported before. 
          Please check for existing issues [here](https://github.com/crdroidandroid/issue_tracker/issues/labels/bug).  
          *Do note that unofficial versions will not get supported since we can not check device specific source.*
    type: markdown
  - attributes: 
      label: Issue type
      options: 
        - "User interface"
        - "Feature not working as intended"
        - "Source code related"
        - "Other"
    type: dropdown
    validations: 
      required: true
  - attributes: 
      description: "Device should be listed as **Device (codename)**"
      label: Device
    type: textarea
    validations: 
      required: true
  - attributes: 
      description: "*Only current still updated source code is listed*"
      label: "crDroid version"
      options: 
        - "crDroid 7"
        - "crDroid 8"
        - "crDroid 9"
    type: dropdown
    validations: 
      required: true
  - attributes: 
      description: "Exact crDroid version **Ex: 8.6**"
      label: Exact version
    type: textarea
    validations: 
      required: true
  - attributes: 
      description: "Simple description of the issue"
      label: "Bug description"
    type: textarea
    validations: 
      required: true
  - attributes: 
      description: "Steps to reproduce the issue"
      label: "Steps to reproduce"
      placeholder: "Step 1. Go to crDroid settings. Step 2. ..."
    type: textarea
    validations: 
      required: true
  - attributes: 
      description: "Please copy and paste any relevant log output.  
        This will be automatically formatted into code, so no need for backticks."
      label: "Relevant log (logcat/build log)"
      render: shell
    type: textarea
    validations: 
      required: true
  - attributes: 
      description: "Add screenshots or videos that show the bug here."
      label: "Screenshots or videos"
      placeholder: "Drag and drop the screenshots/videos into this box."
    type: textarea
    validations: 
      required: false
  - attributes: 
      description: "If applicable, add a possible solution."
      label: Solution
    type: textarea
    validations: 
      required: false
  - attributes: 
      description: "Add additional context here."
      label: "Additional context"
    type: textarea
    validations: 
      required: false
  - attributes: 
      description: "Your issue will be closed if you haven't done these steps."
      label: Acknowledgements
      options: 
        - label: "I've checked device is officially supported (for device specific reports and not source related)."
          required: false
        - label: "I'm running latest version available on crdroid.net for this device"
          required: true
        - label: "I have searched the existing issues and this is a new and no duplicate or related to another open issue."
          required: true
        - label: "I have written a short but informative title."
          required: true
        - label: "I filled out all of the requested information in this issue properly."
          required: true
    id: acknowledgements
    type: checkboxes
