blank_issues_enabled: false
contact_links:
  - name: 📃 Build risingOS
    url: https://github.com/RisingTechOSS/android/
    about: See initial risingOS build documentation
  - name: 🗨 Telegram
    url: https://t.me/RisingOSG
    about: Join the chat on Telegram
